# Generated by Django 6.0.4 on 2026-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='link',
            new_name='button_link',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero Slider'), ('campaign', 'Full Width Campaign Banner'), ('mid_promo_left', 'Mid Promo (Left Side)'), ('mid_promo_right', 'Mid Promo (Right Side)'), ('featured_large', 'Featured Grid (Large Card)'), ('featured_small_top', 'Featured Grid (Small Top Card)'), ('featured_small_bottom', 'Featured Grid (Small Bottom Card)')], default='hero', max_length=30),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
