# Generated by Django 6.0.4 on 2026-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_homesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='clients_logos/')),
            ],
        ),
    ]
