# Generated by Django 6.0.4 on 2026-04-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_happyclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_timescale',
            field=models.CharField(default='3-5 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='emi_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='e.g., AGL32525', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='HTML for specs (e.g., <table>...</table>)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.TextField(blank=True, help_text='Warranty details HTML', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero Slider (Top)'), ('campaign', 'Full Width Campaign Banner'), ('mid_promo_left', 'Mid Promo (Left Side)'), ('mid_promo_right', 'Mid Promo (Right Side)'), ('featured_large', 'Featured Grid (Large Vertical Card)'), ('featured_small_top', 'Featured Grid (Small Top Card)'), ('featured_small_bottom', 'Featured Grid (Small Bottom Card)')], default='hero', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed HTML description'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.productcolor'),
        ),
    ]
