# Generated by Django 6.0.4 on 2026-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productcolor_product_delivery_timescale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='color_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.region'),
        ),
        migrations.AddField(
            model_name='product',
            name='storages',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.storage'),
        ),
    ]
