# Generated by Django 6.0.4 on 2026-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customizationcategory_customizationoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_customizable_mac',
            field=models.BooleanField(default=False),
        ),
    ]
