# Generated by Django 6.0.4 on 2026-05-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_is_customizable_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationcategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
