# Generated by Django 6.0.4 on 2026-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customizationcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationoption',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
