# Generated by Django 6.0.4 on 2026-05-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customizationoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationcategory',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Show this category ONLY if this specific option is selected by the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_categories', to='store.customizationoption'),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='description',
            field=models.TextField(blank=True, help_text='e.g., Boost your processing and graphics rendering speed...', null=True),
        ),
    ]
