# Generated by Django 6.0.4 on 2026-05-17 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customizationcategory_depends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationcategory',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_categories', to='store.customizationoption'),
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
