# Generated by Django 6.0.4 on 2026-05-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customizationcategory_depends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationoption',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Show this option ONLY if this specific parent option is selected (e.g., show 36GB RAM only if M3 Max is selected).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_options', to='store.customizationoption'),
        ),
    ]
