# Generated by Django 6.0.4 on 2026-05-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customizationoption_depends_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationoption',
            name='depends_on',
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl/Cmd to select multiple options. This option will be clickable ONLY if at least one of these is selected.', related_name='dependent_options', to='store.customizationoption'),
        ),
    ]
