# Generated by Django 6.0.4 on 2026-05-18 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_customizationcategory_depends_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationcategory',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='customizationcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customizationoption',
            name='category',
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl/Cmd to select multiple options. This option is clickable ONLY if at least one selected.', related_name='dependent_options', to='store.customizationoption'),
        ),
        migrations.CreateModel(
            name='CustomizationSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='store.customizationcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.customizationsubcategory'),
        ),
    ]
