# Generated by Django 6.0.4 on 2026-05-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_customizationcategory_depends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationcategory',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl/Cmd to select multiple options. This entire category will show ONLY if at least one of these is selected.', related_name='dependent_categories', to='store.customizationoption'),
        ),
    ]
