# Generated by Django 6.0.4 on 2026-05-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customizationcategory_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationsubcategory',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl/Cmd to select multiple options. This sub-category will show ONLY if at least one is selected.', related_name='dependent_sub_categories', to='store.customizationoption'),
        ),
        migrations.AlterField(
            model_name='customizationcategory',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl/Cmd to select multiple options. This entire category will show ONLY if at least one is selected.', related_name='dependent_categories', to='store.customizationoption'),
        ),
    ]
